# 标题
site_name: 学习笔记
site_url: http://www.haoqihan.top

# github网址
repo_url: https://github.com/haoqihan/learning/  
# 主题
# theme: readthedocs
theme: windmill
nav:
    - python笔记:
        - python基础:
            - python基础信息: '1.python笔记/1.python基础/1.python的基本信息.md'
            - 数据类型: '1.python笔记/1.python基础/2.数据类型.md'
            - 深浅拷贝和流程控制: '1.python笔记/1.python基础/3.深浅拷贝和流程控制.md'
            - 文件操作: '1.python笔记/1.python基础/4.文件操作.md'
            - 编码、小数据池和运算符的优先级: '1.python笔记/1.python基础/5.编码,小数据池,运算符的优先级.md'
            - 异常处理: '1.python笔记/1.python基础/6.异常处理.md'
        - 函数部分:
            - 函数的基本信息: '1.python笔记/2.函数部分/1.函数的基本信息.md'
            - 三大器(装饰器,迭代器和生成器): '1.python笔记/2.函数部分/2.三大器(装饰器,迭代器,生成器).md'
            - 关键字,内置函数,匿名函数,递归函数和偏函数: '1.python笔记/2.函数部分/3.关键字,内置函数,匿名函数和递归函数(偏函数).md'
        - 面对对象:
            - 面对对象基础知识: '1.python笔记\3.面对对象\1.面对对象基本知识.md'
            - 面对对象的基本使用: '1.python笔记\3.面对对象\2.面对对象的基本使用.md'
            - 面对对象的魔法方法: '1.python笔记\3.面对对象\3.面对对象的魔法方法.md'
        - 网络编程:
            - 基础知识:  '1.python笔记\4.网络编程\1.网络编程的基本知识.md'
            - 各种协议:  '1.python笔记\4.网络编程\2.各类网络协议.md'
        - 并发编程:
            - 进程: '1.python笔记\5.并发编程\1.进程.md'
            - 线程: '1.python笔记\5.并发编程\2.线程.md'
            - 协程: '1.python笔记\5.并发编程\3.协程.md'
            - IO模型: '1.python笔记\5.并发编程\4.IO模型.md'
        - django基础:
            - 基础命令: '1.python笔记\6.django基础\1.基本命令.md'
            - 路由系统: '1.python笔记\6.django基础\2.路由系统.md'
            - 视图系统: '1.python笔记\6.django基础\3.视图系统.md'
            - 模板系统: '1.python笔记\6.django基础\4.模板系统.md'
            - 中间件: '1.python笔记\6.django基础\5.中间件.md'
            - 模型层: '1.python笔记\6.django基础\6.模型层.md'
            - 表单层: '1.python笔记\6.django基础\7.表单.md'
            - ORM: '1.python笔记\6.django基础\8.ORM.md'
        - Flask基础:
            - 基础知识: '1.python笔记\7.Flask基础\1.flask基础知识.md'
            - Flask和HTTP: '1.python笔记\7.Flask基础\2.Flask和HTTP.md'
            - 模板: '1.python笔记\7.Flask基础\3.模板.md'
            - 表单: '1.python笔记\7.Flask基础\4.表单.md'
            - 数据库: '1.python笔记\7.Flask基础\5.数据库.md'
            - 电子邮件: '1.python笔记\7.Flask基础\6.电子邮件.md'
        - 模块总结:
            - 异步模块: '1.python笔记\8.模块总结\1.异步模块(celery和asyncio).md'
            - API模块: '1.python笔记\8.模块总结\2.API模块(REST framework 和 Flask REST API).md'
    - 前端笔记:
        - html笔记: '2.前端笔记\1.html笔记.md'
        - css笔记: '2.前端笔记\2.css笔记.md'
        - javascript笔记: '2.前端笔记\3.javascript笔记.md'
        - jquery笔记: '2.前端笔记\4.jquery笔记.md'
        - es6笔记: '2.前端笔记\5.es6笔记.md'
        - vue笔记: '2.前端笔记\6.VUE笔记.md'
    - 数据库笔记:
        - mysql数据库: '3.数据库笔记\1.mysql数据库.md'
        - redis数据库: '3.数据库笔记\2.redis数据库.md'
        - MangoDB数据库: '3.数据库笔记\3.MangoDB数据库.md'
        - menmcached数据库: '3.数据库笔记\4.menmcached数据库.md'
    - linux笔记:
        - 基本命令: '4.linux笔记\1.linux的基本命令.md'
        - 进阶命令: '4.linux笔记\2基础命令进阶.md'
        - linux中文件的安装: '4.linux笔记\3linux各种文件的安装.md'
        - docker的使用: '4.linux笔记\4.docker的使用.md'
        - nginx的使用: '4.linux笔记\5.nginx的使用.md'
        - shell编程: '4.linux笔记\6.shell编程.md'
    - 算法笔记:
        - 基本10大算法: '5.算法笔记\基本10大算法.md'
        - 数据结构: '5.算法笔记\数据结构.md'
        - 设计模式: '5.算法笔记\设计模式.md'
    - 爬虫笔记:
        - 爬虫的基本原理: '6.爬虫笔记\1.爬虫的基本原理.md'
        - re模块的使用: '6.爬虫笔记\2.re模块的使用.md'
        - urllib库的使用: '6.爬虫笔记\3.urllib库详解.md'
        - requests库的使用: '6.爬虫笔记\4.requests的基本使用方法.md'
        - bs4库的使用: '6.爬虫笔记\5.bs4模块的基本使用.md'
        - selenium库的使用: '6.爬虫笔记\6.selenium的基本使用.md'
        - pyquery库的使用: '6.爬虫笔记\7.pyquery库的基本使用.md'
        - scrapy框架的使用: '6.爬虫笔记\scrapy框架.md'
    - 数据分析:
        - numpy模块: '9.数据分析\1.numpy模块.md'
        - matplotlib库: '9.数据分析\2.matplotlib库.md'
        - pandas库: '9.数据分析\3.Pandas库的基本使用.md'
    - 奇技淫巧:
        - vim的使用: '奇技淫巧\1.vim的使用笔记.md'
        - markdown笔记: '奇技淫巧\2.Makdown笔记.md'
        - git笔记: '奇技淫巧\3.git笔记.md'
        - jupyter的使用: '奇技淫巧\4.jupyter的使用.md'
        - mkdocs的使用: '奇技淫巧\5.mkdocs的使用.md'
   
